---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	llm(llm)
	handle_tool_call(handle_tool_call)
	__end__([<p>__end__</p>]):::last
	__start__ --> llm;
	handle_tool_call --> llm;
	llm -. &nbsp;end&nbsp; .-> __end__;
	llm -.-> handle_tool_call;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
